### ISSUE TITLE
Error while building - can't get github.com/brocaar/lorawan@v0.0.0-20191105091820-9ed596703a6c

### ISSUE THREAD

**Issue by Famosi** [brocaar/chirpstack-simulator#17]
branch: master

Can't run the command `docker compose run --rm chirpstack-simulator make clean build`. 

It gives me the following error:
```
go: github.com/brocaar/lorawan@v0.0.0-20191105091820-9ed596703a6c: Get "https://proxy.golang.org/github.com/brocaar/lorawan/@v/v0.0.0-20191105091820-9ed596703a6c.mod": dial tcp 142.251.209.49:443: connect: no route to host
make: *** [Makefile:7: build] Error 1
```
I also tried to use the version [v0.0.0-20230609081225-559f55342122](https://pkg.go.dev/github.com/brocaar/lorawan@v0.0.0-20230609081225-559f55342122) of the package. In that case it gives the following:
```
go: github.com/brocaar/lorawan@v0.0.0-20230609081225-559f55342122: missing go.sum entry; to add it:
	go mod download github.com/brocaar/lorawan
make: *** [Makefile:7: build] Error 1

```
 
 Any suggestion? Thanks :)

**Comment by brocaar** [comment]
> Get "https://proxy.golang.org/github.com/brocaar/lorawan/@v/v0.0.0-20191105091820-9ed596703a6c.mod": dial tcp 142.251.209.49:443: connect: no route to host

This is a network issue at your side, e.g. your machine is unable to connect to that host. It looks like it is able to resolve the hostname to IP, but it is unable to connect to it.
