### ISSUE TITLE
Read device, gateway, integration, ... details from file

### ISSUE THREAD

**Issue by guftall** [brocaar/chirpstack-simulator#2]
Hi, thanks for publishing this useful software. We use it in our projects a lot, but there is a pain when i want to test lora integration to ThingsBoard, i have to insert integrations and device access tokens manually every time i restart the simulator.
Decided to add a feature that simulator read all dynamic generated data like device id, gateway id and so on from a file. How do you think about this feature? is there any critical problem that avoid simulator from working correctly by this method? if no, i will be happy to create a pull request and implement that.

**Comment by brocaar** [comment]
Thanks for your proposal, but I would prefer to not merge this in to keep the provided simulator as easy as possible. Please note that next to the provided binary (that you can compile), you can also use this code as a library. See for example: https://github.com/brocaar/chirpstack-simulator/blob/master/examples/single_uplink/main.go

**Comment by guftall** [comment]
That's a good notice, i would use that API for initialization of devices. Thanks and stay safe.
